修改编译的bug

diff --git a/.github/workflows/build-ai.yaml b/.github/workflows/build-ai.yaml
--- a/.github/workflows/build-ai.yaml
+++ b/.github/workflows/build-ai.yaml
@@ -202,23 +202,9 @@ jobs:
           set -euo pipefail
           mkdir -p repo/packages/${{ env.TARGET_ARCH }}
           mkdir -p repo/apk-keys
-          if [ -f ".github/$APK_ASSET_NAME" ]; then
-            cp ".github/$APK_ASSET_NAME" .github/luci-homeproxy-avkiller_aarch64_generic.apk 2>/dev/null || true
-          else
-            echo "::error::APK not found: $APK_ASSET_NAME"
-            exit 1
-          fi
-
-          if [ -f ".github/$IPK_ASSET_NAME" ]; then
-            cp ".github/$IPK_ASSET_NAME" .github/luci-homeproxy-avkiller_aarch64_generic.ipk 2>/dev/null || true
-          else
-            echo "::error::IPK not found: $IPK_ASSET_NAME"
-            exit 1
-          fi
           echo "显示当前目录的文件列表"
           find .github -type f
           # ls -al .github
-          exit 1
           cp .github/*.ipk repo/packages/${{ env.TARGET_ARCH }}/ 2>/dev/null || true
           cp .github/*.apk repo/packages/${{ env.TARGET_ARCH }}/ 2>/dev/null || true
 
@@ -269,6 +255,20 @@ jobs:
         run: |
           mkdir -p dist/
           # 寻找所有 ipk, apk, gz, sig 并强行复制到 dist/ 根目录下（去掉深层目录结构）
+          # 重命名一部分文件便于固定文件名
+          if [ -f ".github/$APK_ASSET_NAME" ]; then
+            cp ".github/$APK_ASSET_NAME" dist/luci-homeproxy-avkiller_aarch64_generic.apk 2>/dev/null || true
+          else
+            echo "::error::APK not found: $APK_ASSET_NAME"
+            exit 1
+          fi
+
+          if [ -f ".github/$IPK_ASSET_NAME" ]; then
+            cp ".github/$IPK_ASSET_NAME" dist/luci-homeproxy-avkiller_aarch64_generic.ipk 2>/dev/null || true
+          else
+            echo "::error::IPK not found: $IPK_ASSET_NAME"
+            exit 1
+          fi
           find repo/ -type f \( -name "*.ipk" -o -name "*.apk" -o -name "*.gz" -o -name "*.adb" -o -name "*.sig" \) -exec cp {} dist/ \;
           # 拷贝公共证书
           cp "${{ github.workspace }}/homeproxy-custom.pem" dist/homeproxy-apk-public.pub
